name: Build TWRP on Homeserver

on:
  workflow_dispatch:

jobs:
  build-twrp:
    runs-on: self-hosted   # nutzt deinen Runner "homeserver" in der Default-Gruppe
    

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git curl bc build-essential \
          gcc-multilib g++-multilib libncurses5-dev \
          libssl-dev flex bison ccache lib32z1 lib32ncurses6 \
          lib32stdc++6 python-is-python3 repo

    - name: Initialize TWRP repo (twrp-11)
      run: |
        mkdir -p source
        cd source
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11 --depth=1
        repo sync -c --no-clone-bundle --no-tags -j4

    - name: Clone device tree for SM-A137F
      run: |
        cd source
        mkdir -p device/samsung
        git clone https://github.com/edward0181/android_device_samsung_a13ve device/samsung/a13ve

    - name: Clone kernel source (optional)
      run: |
        cd source
        mkdir -p kernel/samsung
        git clone https://github.com/edward0181/android_kernel_samsung_a13ve kernel/samsung/a13ve

    - name: Build recovery image
      run: |
        cd source
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch twrp_a13ve-eng
        mka recoveryimage

    - name: Copy recovery.img to output folder
      run: |
        mkdir -p output
        cp source/out/target/product/a13ve/recovery.img output/

    - name: Upload recovery.img
      uses: actions/upload-artifact@v4
      with:
        name: recovery-image
        path: output/recovery.img
